# Generated by Django 3.1.7 on 2021-03-27 17:17

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(4)])),
                ('password', models.CharField(max_length=8, validators=[django.core.validators.MinLengthValidator(8)])),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=50)),
                ('movie_language', models.CharField(max_length=30)),
                ('movie_duration', models.IntegerField()),
                ('movie_description', models.CharField(default='', max_length=256)),
                ('movie_release_date', models.DateField(default=datetime.datetime.now)),
                ('image', models.ImageField(default='', upload_to='media/images')),
            ],
        ),
    ]
