# Generated by Django 3.1.7 on 2021-03-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='', upload_to='static/media/images'),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_description',
            field=models.CharField(default='', max_length=256),
        ),
    ]
