# Generated by Django 3.1.7 on 2021-04-14 05:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20210406_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_screening',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_date', models.DateField()),
                ('show_price', models.IntegerField()),
                ('show_time', models.IntegerField(choices=[(9, 'Nine'), (11, 'Eleven'), (13, 'Thirteen'), (15, 'Fifteen'), (17, 'Seventeen'), (19, 'Nineteen')])),
                ('show_seats', models.IntegerField(default=80)),
                ('show_booked_seats', models.IntegerField(default=0)),
                ('show_movie', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='show_movie', to='movie.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_tickets', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.show')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.customer')),
            ],
        ),
    ]
