# Generated by Django 3.1.7 on 2021-03-19 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_customer_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_release_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
