# Generated by Django 3.1.7 on 2021-03-19 15:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_movie_movie_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
